name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
      - name: Now it is
        run: date
      - name: Directory content
        run: ls -l
